"""empty message

Revision ID: 02fb75b5e689
Revises: 2fb0a189cb79
Create Date: 2022-03-02 16:18:33.433736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fb75b5e689'
down_revision = '2fb0a189cb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.alter_column('booking', 'booking_slot',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'booking_slot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('seats',
    sa.Column('seat_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('coach_id', sa.INTEGER(), nullable=False),
    sa.Column('is_booked', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('seat_id', 'date', 'coach_id')
    )
    # ### end Alembic commands ###
