"""empty message

Revision ID: 638fee2c9e9c
Revises: 02fb75b5e689
Create Date: 2022-03-02 16:19:45.350897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638fee2c9e9c'
down_revision = '02fb75b5e689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'booking_slot',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'booking_slot',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
